# @package _global_
env_name: url_ant
num_train_steps: 1e6
eval_freq: 1000

# Environment-specific overrides:
learn_temp:
  init_targ_entr: 0
  final_targ_entr: -2
  entr_decay_factor: 4.0

agent:
  horizon: 3
  warmup_steps: 10000

